version: 2

models:
  - name: stg_overlap_subscriptions
    description: "A starter dbt model"
    columns:
      - name: subscription_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
